# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb312793d5c44ed67090e47b766746ef7c7ca96f0a5d6489987b3dc23eb498fe0fcc7d66b5a8ddb057f54f9a31aed4922603d9b2408b669bc66be3c172d7a4b5

test:
  secret_key_base: a9c0225408e1e951f1fd4d10d23fd32b17e6fd8e88c76a8091bbc6a7990fe0978ddc00c43afd6d0e11675ed6b865c9f5c35bd5d6ec71456e2cfcb66b28d19b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
